FROM apache/airflow:2.7.1-python3.9

USER root
RUN apt-get update && apt-get install -y gcc python3-dev

USER airflow
# Pydantic వెర్షన్‌ని 1.10.13 కి లాక్ చేస్తున్నాం
RUN pip install --no-cache-dir --default-timeout=1000 \
    pandas \
    pydantic==1.10.13 \
    evidently==0.4.15 \
    sqlalchemy \
    psycopg2-binary \
    mlflow